"""baseline schema v1

Revision ID: aecfe72dfde6
Revises: 
Create Date: 2026-09-08 16:55:43.351848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aecfe72dfde6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('linkKey', sa.String(length=32), nullable=True),
    sa.Column('linkId', sa.String(length=32), nullable=True),
    sa.Column('isRead', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_createdAt'), 'notifications', ['createdAt'], unique=False)
    op.create_index(op.f('ix_notifications_isRead'), 'notifications', ['isRead'], unique=False)
    op.create_index(op.f('ix_notifications_uid'), 'notifications', ['uid'], unique=False)
    op.create_table('operation_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('operatorName', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('entityKey', sa.String(length=32), nullable=True),
    sa.Column('entityLabel', sa.String(length=32), nullable=True),
    sa.Column('recordId', sa.String(length=32), nullable=True),
    sa.Column('sid', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_logs_action'), 'operation_logs', ['action'], unique=False)
    op.create_index(op.f('ix_operation_logs_createdAt'), 'operation_logs', ['createdAt'], unique=False)
    op.create_index(op.f('ix_operation_logs_entityKey'), 'operation_logs', ['entityKey'], unique=False)
    op.create_index(op.f('ix_operation_logs_recordId'), 'operation_logs', ['recordId'], unique=False)
    op.create_index(op.f('ix_operation_logs_sid'), 'operation_logs', ['sid'], unique=False)
    op.create_index(op.f('ix_operation_logs_uid'), 'operation_logs', ['uid'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('passwordHash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('sex', sa.String(length=8), nullable=True),
    sa.Column('nation', sa.String(length=16), nullable=True),
    sa.Column('politicsStatus', sa.String(length=16), nullable=True),
    sa.Column('birthday', sa.String(length=16), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('classId', sa.String(length=32), nullable=True),
    sa.Column('periods', sa.String(length=16), nullable=True),
    sa.Column('college', sa.String(length=64), nullable=True),
    sa.Column('major', sa.String(length=64), nullable=True),
    sa.Column('origin', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('counsellorId', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['counsellorId'], ['users.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_classId'), 'users', ['classId'], unique=False)
    op.create_index(op.f('ix_users_college'), 'users', ['college'], unique=False)
    op.create_index(op.f('ix_users_counsellorId'), 'users', ['counsellorId'], unique=False)
    op.create_index(op.f('ix_users_periods'), 'users', ['periods'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    op.create_table('certificates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sid', sa.String(length=32), nullable=False),
    sa.Column('project', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('date', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('auditor', sa.String(length=64), nullable=True),
    sa.Column('opinion', sa.String(length=255), nullable=True),
    sa.Column('auditTime', sa.String(length=32), nullable=True),
    sa.Column('publicEnd', sa.String(length=32), nullable=True),
    sa.Column('files', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['users.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_sid'), 'certificates', ['sid'], unique=False)
    op.create_index(op.f('ix_certificates_status'), 'certificates', ['status'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sid', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('createdAt', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['users.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_sid'), 'chat_sessions', ['sid'], unique=False)
    op.create_table('experiences',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sid', sa.String(length=32), nullable=False),
    sa.Column('startDate', sa.String(length=16), nullable=False),
    sa.Column('endDate', sa.String(length=16), nullable=False),
    sa.Column('college', sa.String(length=64), nullable=False),
    sa.Column('major', sa.String(length=64), nullable=False),
    sa.Column('classId', sa.String(length=32), nullable=True),
    sa.Column('eyewitness', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['sid'], ['users.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiences_sid'), 'experiences', ['sid'], unique=False)
    op.create_table('gpa_comps',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sid', sa.String(length=32), nullable=False),
    sa.Column('semester', sa.String(length=16), nullable=False),
    sa.Column('college', sa.String(length=64), nullable=False),
    sa.Column('major', sa.String(length=64), nullable=False),
    sa.Column('mutual', sa.Float(), nullable=False),
    sa.Column('comp', sa.Float(), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=False),
    sa.Column('gpaRank', sa.Integer(), nullable=False),
    sa.Column('compRank', sa.Integer(), nullable=False),
    sa.Column('maxRank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['users.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpa_comps_sid'), 'gpa_comps', ['sid'], unique=False)
    op.create_table('honors',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sid', sa.String(length=32), nullable=False),
    sa.Column('project', sa.String(length=128), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('date', sa.String(length=16), nullable=False),
    sa.Column('team', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('auditor', sa.String(length=64), nullable=True),
    sa.Column('opinion', sa.String(length=255), nullable=True),
    sa.Column('auditTime', sa.String(length=32), nullable=True),
    sa.Column('publicEnd', sa.String(length=32), nullable=True),
    sa.Column('files', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['users.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_honors_sid'), 'honors', ['sid'], unique=False)
    op.create_index(op.f('ix_honors_status'), 'honors', ['status'], unique=False)
    op.create_table('innovations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sid', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('project', sa.String(length=128), nullable=False),
    sa.Column('implementation', sa.String(length=255), nullable=True),
    sa.Column('honor', sa.String(length=64), nullable=True),
    sa.Column('deadline', sa.String(length=16), nullable=True),
    sa.Column('date', sa.String(length=16), nullable=True),
    sa.Column('post', sa.String(length=32), nullable=True),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('auditor', sa.String(length=64), nullable=True),
    sa.Column('opinion', sa.String(length=255), nullable=True),
    sa.Column('auditTime', sa.String(length=32), nullable=True),
    sa.Column('publicEnd', sa.String(length=32), nullable=True),
    sa.Column('files', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['users.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_innovations_category'), 'innovations', ['category'], unique=False)
    op.create_index(op.f('ix_innovations_sid'), 'innovations', ['sid'], unique=False)
    op.create_index(op.f('ix_innovations_status'), 'innovations', ['status'], unique=False)
    op.create_table('objections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('recordId', sa.String(length=32), nullable=False),
    sa.Column('recordLabel', sa.String(length=32), nullable=False),
    sa.Column('recordTitle', sa.String(length=128), nullable=False),
    sa.Column('sid', sa.String(length=32), nullable=False),
    sa.Column('objectorUid', sa.String(length=32), nullable=False),
    sa.Column('objectorName', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('handledBy', sa.String(length=64), nullable=True),
    sa.Column('handledTime', sa.String(length=32), nullable=True),
    sa.Column('createdAt', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['users.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objections_key'), 'objections', ['key'], unique=False)
    op.create_index(op.f('ix_objections_recordId'), 'objections', ['recordId'], unique=False)
    op.create_index(op.f('ix_objections_sid'), 'objections', ['sid'], unique=False)
    op.create_index(op.f('ix_objections_status'), 'objections', ['status'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sid', sa.String(length=32), nullable=False),
    sa.Column('team', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('post', sa.String(length=32), nullable=False),
    sa.Column('startDate', sa.String(length=16), nullable=False),
    sa.Column('endDate', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('auditor', sa.String(length=64), nullable=True),
    sa.Column('opinion', sa.String(length=255), nullable=True),
    sa.Column('auditTime', sa.String(length=32), nullable=True),
    sa.Column('publicEnd', sa.String(length=32), nullable=True),
    sa.Column('files', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['users.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_sid'), 'organizations', ['sid'], unique=False)
    op.create_index(op.f('ix_organizations_status'), 'organizations', ['status'], unique=False)
    op.create_table('parties',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sid', sa.String(length=32), nullable=False),
    sa.Column('date', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('boss', sa.String(length=32), nullable=True),
    sa.Column('leader', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('auditor', sa.String(length=64), nullable=True),
    sa.Column('opinion', sa.String(length=255), nullable=True),
    sa.Column('auditTime', sa.String(length=32), nullable=True),
    sa.Column('publicEnd', sa.String(length=32), nullable=True),
    sa.Column('files', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['users.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_sid'), 'parties', ['sid'], unique=False)
    op.create_index(op.f('ix_parties_status'), 'parties', ['status'], unique=False)
    op.create_table('practices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sid', sa.String(length=32), nullable=False),
    sa.Column('team', sa.String(length=128), nullable=False),
    sa.Column('startDate', sa.String(length=16), nullable=False),
    sa.Column('endDate', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('theme', sa.String(length=128), nullable=False),
    sa.Column('sponsor', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('auditor', sa.String(length=64), nullable=True),
    sa.Column('opinion', sa.String(length=255), nullable=True),
    sa.Column('auditTime', sa.String(length=32), nullable=True),
    sa.Column('publicEnd', sa.String(length=32), nullable=True),
    sa.Column('files', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['users.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practices_sid'), 'practices', ['sid'], unique=False)
    op.create_index(op.f('ix_practices_status'), 'practices', ['status'], unique=False)
    op.create_table('voluntarys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sid', sa.String(length=32), nullable=False),
    sa.Column('project', sa.String(length=128), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('sponsor', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('auditor', sa.String(length=64), nullable=True),
    sa.Column('opinion', sa.String(length=255), nullable=True),
    sa.Column('auditTime', sa.String(length=32), nullable=True),
    sa.Column('publicEnd', sa.String(length=32), nullable=True),
    sa.Column('files', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['users.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voluntarys_sid'), 'voluntarys', ['sid'], unique=False)
    op.create_index(op.f('ix_voluntarys_status'), 'voluntarys', ['status'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sessionId', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['sessionId'], ['chat_sessions.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_sessionId'), 'chat_messages', ['sessionId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_sessionId'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_voluntarys_status'), table_name='voluntarys')
    op.drop_index(op.f('ix_voluntarys_sid'), table_name='voluntarys')
    op.drop_table('voluntarys')
    op.drop_index(op.f('ix_practices_status'), table_name='practices')
    op.drop_index(op.f('ix_practices_sid'), table_name='practices')
    op.drop_table('practices')
    op.drop_index(op.f('ix_parties_status'), table_name='parties')
    op.drop_index(op.f('ix_parties_sid'), table_name='parties')
    op.drop_table('parties')
    op.drop_index(op.f('ix_organizations_status'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_sid'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_objections_status'), table_name='objections')
    op.drop_index(op.f('ix_objections_sid'), table_name='objections')
    op.drop_index(op.f('ix_objections_recordId'), table_name='objections')
    op.drop_index(op.f('ix_objections_key'), table_name='objections')
    op.drop_table('objections')
    op.drop_index(op.f('ix_innovations_status'), table_name='innovations')
    op.drop_index(op.f('ix_innovations_sid'), table_name='innovations')
    op.drop_index(op.f('ix_innovations_category'), table_name='innovations')
    op.drop_table('innovations')
    op.drop_index(op.f('ix_honors_status'), table_name='honors')
    op.drop_index(op.f('ix_honors_sid'), table_name='honors')
    op.drop_table('honors')
    op.drop_index(op.f('ix_gpa_comps_sid'), table_name='gpa_comps')
    op.drop_table('gpa_comps')
    op.drop_index(op.f('ix_experiences_sid'), table_name='experiences')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_chat_sessions_sid'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_certificates_status'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_sid'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_periods'), table_name='users')
    op.drop_index(op.f('ix_users_counsellorId'), table_name='users')
    op.drop_index(op.f('ix_users_college'), table_name='users')
    op.drop_index(op.f('ix_users_classId'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_operation_logs_uid'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_sid'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_recordId'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_entityKey'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_createdAt'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_action'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index(op.f('ix_notifications_uid'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_isRead'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_createdAt'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
